export const superSmall = `*
AA a
BB b
CC c

1: AA,BB,CC: AA,BB,CC
2: CC,AA: CC,AA
3: CC,DD,AA: CC,DD,AA`;

export const backToTheFuture = `* BackToTheFuture
MM Marty McFly
DB Dr Emmett Brown
GW Goldie Wilson
JP Jennifer Parker
MS Mr Strickland
HJ High School Band Audition Judge
PI Pinhead
P1 Pinhead
P2 Pinhead
CL Clocktower Lady
GM George McFly
BT Biff Tannen
DM Dave McFly
LB Lorraine Baines
LM Linda McFly
TE Terrorist
TD Terrorist Van Driver
MP Ma Peabody
DP Daughter Peabody
PP Pa Peabody
SP Sherman Peabody
LO Lou
MA Match
SK Skinhead
3D 3D
SB Sam Baines
ST Stella Baines
SA Sally Baines
MB Milton Baines
CO Cop
BE Marvin Berry
B2 Bystander 2
B1 Bystander 1
RB Red Thomas  the Bum

203  : MM : MM
293  : MM;DB : DB
359  : MM,DB : MM,DB
404  : GW;MM;DB : GW
409  : GW,MM;DB : MM,GW
428  : GW;MM;MS;DB : MS
480  : GW;JP,MM,MS;DB : MM,JP,MS
487  : GW;P2,P1,PI,JP;MM;MS;DB : PI,P1,P2,JP
537  : GW;HJ,P2,P1,PI,JP,MM;MS;DB : HJ,MM,PI,P1,P2,JP
544  : GW;CL,JP,MM;MS;DB : MM,JP,CL
706  : GW,CL,JP,MM;MS;DB : GW,MM,JP,CL
742  : GW;JP;BT,GM;MM;MS;DB : GM,BT
874  : GW;JP;BT,GM,MM;MS;DB : MM,GM,BT
890  : GW;JP;BT;GM;MS;MM;LB,DB,LM : LB,LM,DB
1084 : GW;JP;BT;MS;GM,LB,MM,DB,LM,DM : GM,MM,DM,LB,LM,DB
1110 : GW;JP;BT;GM;MS;LB;MM;DB;LM;DM : DB
1722 : JP;GW;BT;GM;MS;LB;MM,DB;LM;DM : MM,DB
1738 : JP;GW;BT;GM;MS;LB;MM;DB;TD,TE;LM;DM : TE,TD
1891 : JP;GW;BT;GM;MS;LB;MM,DB,TD,TE;LM;DM : MM,DB,TE,TD
1912 : JP;GW;BT;GM;LB;MS;MM;MP,DP,PP,SP;DB;TD;TE;LM;DM : MP,DP,PP,SP
2019 : JP;GW;BT;GM;LB;MS;MM,MP,DP,PP,SP;DB;TD;TE;LM;DM : MM,MP,DP,PP,SP
2114 : JP;GW;BT;GM;MM;LB;MS;DB;TD;TE;LM;DM : MM
2245 : JP;GW;BT;GM;MM;LB;MS;DB;TD;TE;LM;DM : MM
2327 : JP;GW,SK,MA,3D,BT;GM;MM;LB;MS;DB;TD;TE;LM;DM : MA,BT,SK,3D,GW
2483 : JP;LO,GW,SK,MA,3D,BT,GM,MM;LB;MS;DB;TD;TE;LM;DM : MM,LO,GM,MA,BT,SK,3D,GW
2501 : JP;LO;GW;SK;MA;3D;BT;GM;SB,LB;MM;MS;DB;TD;TE;LM;DM : LB,SB
2549 : JP;LO;GW;SK;MA;3D;BT;GM,SB,LB,MM;MS;DB;TD;TE;LM;DM : MM,GM,LB,SB
2693 : JP;LO;GW;SK;MA;3D;BT;GM;MB,SA,SB;LB;MM;MS;DB;TD;TE;LM;DM : SB,SA,MB
2874 : JP;LO;GW;SK;MA;3D;BT;GM;ST,MB,SA,SB,LB,MM;MS;DB;TD;TE;LM;DM : MM,LB,ST,SB,SA,MB
2905 : JP;LO;GW;SK;MA;3D;BT;LB;MS;GM;MM;DB;TD;TE;LM;DM : DB
3067 : JP;LO;GW;SK;MA;3D;BT;LB;MS;GM;MM,DB;TD;TE;LM;DM : MM,DB
3135 : JP;LO;GW;SK;MA;3D;BT;LB;MS;GM;MM,DB;TD;TE;LM;DM : MM,DB
3342 : JP;LO;GW;SK;MA;3D;BT;LB;MS;GM;MM;DB;TD;TE;LM,DM : DM,LM
3353 : JP;LO;GW;SK;MA;3D;BT;LB;MS;GM;MM,DB,LM,DM;TD;TE : MM,DB,DM,LM
3392 : JP;LO;GW;SK;MA;3D,BT,LB,MS;GM;MM;DB;LM;DM;TD;TE : MS,LB,3D,BT
3678 : JP;LO;GW;SK;MA;3D,BT,LB,MS,GM,MM,DB;LM;DM;TD;TE : MM,DB,GM,MS,LB,3D,BT
3716 : JP;LO;GW;SK;MA;3D;BT;LB;MS;GM;MM;DB;LM,DM;TD;TE : DM,LM
3720 : JP;LO;GW;SK;MA;3D;BT;LB;MS;GM,MM,LM,DM;DB;TD;TE : MM,GM,DM,LM
3730 : JP;LO;GW;SK;MA;3D;BT;LB;MS;GM;MM;LM;DM;DB;TD;TE : MM
3773 : JP;LO;GW;SK;MA;3D;BT;LB;MS;GM,MM;LM;DM;DB;TD;TE : GM,MM
3813 : JP;LO;GW;SK;MA;3D;BT;LB;GM;MM;MS;LM;DM;DB;TD;TE : LB
3845 : JP;LO;GW;SK;MA;3D;BT;LB,GM,MM;MS;LM;DM;DB;TD;TE : GM,MM,LB
3907 : JP;LO;GW;SK,MA,3D,BT;GM;LB;MM;MS;LM;DM;DB;TD;TE : MA,BT,SK,3D
3958 : JP;LO,GW,SK,MA,3D,BT,GM,LB,MM;MS;LM;DM;DB;TD;TE : MM,GM,GW,LB,LO,MA,BT,SK,3D
3966 : JP;GW,SK,MA,3D,BT,GM,LB;MM;DB;MS;LM;DM;TD;TE : MA,BT,SK,3D,LB,GM,GW
4090 : JP;GW,SK,MA,3D,BT,GM,MM,LB;DB;MS;LM;DM;TD;TE : MM,MA,BT,SK,3D,LB,GM,GW
4094 : JP;SK;MA;3D;BT;GM;MM;LB,DB;MS;LM;DM;TD;TE : DB,LB
4362 : JP;SK;MA;3D;BT;GM;MM,LB,DB;MS;LM;DM;TD;TE : MM,DB,LB
4469 : JP;SK;MA;3D;BT;GM,MM;LB;DB;LM;MS;DM;TD;TE : MM,GM
4540 : JP;SK;MA;3D;BT;GM;LB;MM,DB;LM;MS;DM;TD;TE : MM,DB
4572 : JP;SK;MA;3D;BT;GM;LB;MM;CO,DB;LM;MS;DM;TD;TE : DB,CO
4602 : JP;SK;MA;3D;BT;GM;LB;MM,CO,DB;LM;MS;DM;TD;TE : MM,DB,CO
4815 : JP;SK,MA,3D,BT;GM;LB;MM;DB;LM;MS;DM;TD;TE : BT,MA,SK,3D
4896 : JP;SK,MA,3D,BT,BE,GM,LB,MM;DB;LM;MS;DM;TD;TE : BE,GM,MM,LB,BT,MA,SK,3D
4962 : JP;BT;BE;GM;LB;MM,LM,DB;MS;DM;TD;TE : MM,LM,DB
5078 : JP;BT,BE,GM,LB,MM,LM,DB;MS;DM;TD;TE : GM,LB,BT,BE,MM,LM,DB
5177 : JP;BT;BE;GM;LB;MM;B1,B2,LM,MS;DM;DB;TD;TE : LM,B2,B1,MS
5472 : JP;BT;BE,GM,LB,MM,B1,B2,LM,MS,DM;DB;TD;TE : MM,BE,GM,LB,DM,LM,B2,B1,MS
5513 : JP;BT;GM;LB;LM,DM;DB;MM;TD;TE : DM,LM
6103 : JP;BT;GM;LB;LM,DM,DB,MM;TD;TE : DB,MM,DM,LM
6147 : JP;BT;GM;LB;LM;DM;DB;MM,TD;TE : MM,TD
6197 : JP;BT;GM;LB;LM;DM;DB;RB,MM,TD;TE : RB,MM,TD
6207 : JP;BT;GM;LB;LM;DM;DB;MM;TD,TE : TE,TD
6333 : JP;BT;GM;LB;LM;DM;DB,MM,TD,TE : MM,DB,TE,TD
6400 : JP;BT;GM;LB;LM;DM;DB,MM : MM,DB
6477 : JP,BT,GM,LB,DB;LM;DM;MM : GM,LB,BT,JP,DB
6709 : JP,BT,GM,LB,DB,LM,DM,MM : MM,DM,LM,GM,LB,BT,JP,DB`
